Make silent an errors

diff --git a/src/openbcm/debian/rules b/src/openbcm/debian/rules
--- a/src/openbcm/debian/rules
+++ b/src/openbcm/debian/rules
@@ -1,20 +1,42 @@
 #!/usr/bin/make -f
+# -*- makefile -*-
+# Sample debian/rules that uses debhelper.
+# This file was originally written by Joey Hess and Craig Small.
+# As a special exception, when this file is copied by dh-make into a
+# dh-make output file, you may use that output file without restriction.
+# This special exception was added by Craig Small in version 0.37 of dh-make.
+#
+# This version is for a hypothetical package that can build a kernel modules
+# architecture-dependant package via make-kpkg, as well as an
+# architecture-independent module source package, and other packages
+# either dep/indep for things like common files or userspace components
+# needed for the kernel modules.
 
-export DH_VERBOSE=1
+# Uncomment this to turn on verbose mode.
+#export DH_VERBOSE=1
 
+
+
+
+# some default definitions, important!
+#
 # Name of the source package
 psource:=openbcm-source
 
 # The short upstream name, used for the module source directory
 sname:=openbcm
 
+### KERNEL SETUP
+### Setup the stuff needed for making kernel module packages
+### taken from /usr/share/kernel-package/sample.module.rules
+
+PKG_NAME=openbcm_6.5.21_amd64.deb
 # prefix of the target package name
 PACKAGE=openbcm
-PKG_NAME ?= openbcm
 # modifieable for experiments or debugging m-a
-
-# %:
-# 	dh $@
+MA_DIR ?= /usr/share/modass
+KVERSION ?= 5.10.0-23-2-amd64
+KERNVERSION ?= 5.10.0-23-2
 
 platform=x86-smp_generic_64-2_6
 TARGET=unix-user
@@ -22,21 +44,17 @@ TARGET=unix-user
 SDKLT=/sonic/src/OpenBCM/sdk-6.5.21/libs/sdklt
 SDK=/sonic/src/OpenBCM/sdk-6.5.21
 
-MA_DIR ?= /usr/share/modass
-KVERSION ?= 5.10.0-23-2-amd64
-KERNVERSION ?= 5.10.0-23-2
-
 # load generic variable handling
 -include $(MA_DIR)/include/generic.make
 # load default rules, including kdist, kdist_image, ...
 -include $(MA_DIR)/include/common-rules.make
 
-sdk: sdk_libs sdklt_libs system_libs
+sdk: sdk sdklt kernel_module
 
 include $(SDK)/make/Make.config
 
-system_libs:
-	echo "Prepare system_libs"
+kernel_module:
+	echo "Prepare kernel_module"
 	LINUX_UAPI_SPLIT=1 DEBIAN_LINUX_HEADER=1 BUILD_KNET_CB=1 \
 	BUILD_SDKLT=1 BUILD_AAPL=1 LTSW_CHIPS=1 SYSOK=1 \
 	KERNDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
@@ -53,15 +71,8 @@ ifdef BUILD_KNET
 	$(MAKE) -C $(SDKLT)/linux/knet SDK=$(SDKLT) LKM_BLDDIR=$(SDK)/kbuild
 endif
 
-# LINUX_UAPI_SPLIT=1 DEBIAN_LINUX_HEADER=1 BUILD_KNET_CB=1 \
-# BUILD_SDKLT=1 BUILD_AAPL=1 LTSW_CHIPS=1 SYSOK=1 \
-# KERNDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
-# KERNEL_SRC=/usr/src/linux-headers-$(KERNVERSION)-amd64 \
-# KDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
-# $(MAKE) -C $(SDK)/systems/bde/linux/user CFLAGS="$(CFLAGS) -I$(SDK)/system/bde/linux/include"
-
-sdk_libs:
-	echo "Prepare sdk_libs"
+sdk:
+	echo "Prepare sdk"
 	LINUX_UAPI_SPLIT=1 DEBIAN_LINUX_HEADER=1 BUILD_KNET_CB=1 \
 	BUILD_SDKLT=1 BUILD_AAPL=1 LTSW_CHIPS=1 SYSOK=1 \
 	KERNDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
@@ -75,8 +86,8 @@ sdk_libs:
 	KDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
 	$(MAKE) -C $(SDK) TARGET=$(TARGET) platform=$(platform)
 
-sdklt_libs:
-	echo "Prepare sdklt_libs"
+sdklt:
+	echo "Prepare SDKLT libs"
 	LINUX_UAPI_SPLIT=1 DEBIAN_LINUX_HEADER=1 BUILD_KNET_CB=1 \
 	BUILD_SDKLT=1 BUILD_AAPL=1 LTSW_CHIPS=1 SYSOK=1 \
 	KERNDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
@@ -84,22 +95,21 @@ sdklt_libs:
 	KDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
 	$(MAKE) -C $(SDKLT) SDK=$(SDKLT)
 
-prepare_sdk:
-	echo "Prepare SDK"
+sdk_env:
+	echo "Prepare SDK env"
 	# create links
-	cd /; sudo mkdir -p /lib/modules/$(KERNVERSION)-amd64
-	cd /; sudo rm /lib/modules/$(KERNVERSION)-amd64/build
-	cd /; sudo rm /lib/modules/$(KERNVERSION)-amd64/source
-	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-common/ /lib/modules/$(KERNVERSION)-amd64/source
-	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/ /lib/modules/$(KERNVERSION)-amd64/build
-	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/include/generated/ /usr/src/linux-headers-$(KERNVERSION)-common/include/generated
-	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/arch/x86/include/generated/ /usr/src/linux-headers-$(KERNVERSION)-common/arch/x86/include/generated
-	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/arch/x86/module.lds /usr/src/linux-headers-$(KERNVERSION)-common/arch/x86/module.lds
-	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/include/config/ /usr/src/linux-headers-$(KERNVERSION)-common/include/config
-	cd /; sudo cp /usr/src/linux-headers-$(KERNVERSION)-amd64/Module.symvers /usr/src/linux-headers-$(KERNVERSION)-common/Module.symvers
+	cd /; sudo mkdir -p /lib/modules/$(KERNVERSION)-amd64 2>/dev/null || true
+	cd /; sudo rm /lib/modules/$(KERNVERSION)-amd64/build 2>/dev/null || true
+	cd /; sudo rm /lib/modules/$(KERNVERSION)-amd64/source 2>/dev/null || true
+	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-common/ /lib/modules/$(KERNVERSION)-amd64/source 2>/dev/null || true
+	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/ /lib/modules/$(KERNVERSION)-amd64/build 2>/dev/null || true
+	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/include/generated/ /usr/src/linux-headers-$(KERNVERSION)-common/include/generated 2>/dev/null || true
+	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/arch/x86/include/generated/ /usr/src/linux-headers-$(KERNVERSION)-common/arch/x86/include/generated 2>/dev/null || true
+	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/arch/x86/module.lds /usr/src/linux-headers-$(KERNVERSION)-common/arch/x86/module.lds 2>/dev/null || true
+	cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/include/config/ /usr/src/linux-headers-$(KERNVERSION)-common/include/config 2>/dev/null || true
+	cd /; sudo cp /usr/src/linux-headers-$(KERNVERSION)-amd64/Module.symvers /usr/src/linux-headers-$(KERNVERSION)-common/Module.symvers 2>/dev/null || true
 	mkdir -p $(SDK)/kbuild
 
-	# Add here command to compile/build the package.
 	SDK=/sonic/src/OpenBCM/sdk-6.5.21 \
 	LINUX_UAPI_SPLIT=1 DEBIAN_LINUX_HEADER=1 BUILD_KNET_CB=1 \
 	BUILD_SDKLT=1 BUILD_AAPL=1 LTSW_CHIPS=1 SYSOK=1 \
@@ -108,11 +118,49 @@ prepare_sdk:
 	KDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
 	$(MAKE) -C $(SDK)/systems/bde/linux/user CFLAGS="$(CFLAGS) -I$(SDK)/systems/bde/linux/include"
 
-clean:
+# module assistant calculates all needed things for us and sets
+# following variables:
+# KSRC (kernel source directory), KVERS (kernel version string), KDREV
+# (revision of the Debian kernel-image package), CC (the correct
+# compiler), VERSION (the final package version string), PKGNAME (full
+# package name with KVERS included), DEB_DESTDIR (path to store DEBs)
 
-build: prepare_sdk sdk
-	echo "From build ---"
-	# # create links
+# The kdist_config target is called by make-kpkg modules_config and
+# by kdist* rules by dependency. It should configure the module so it is
+# ready for compilation (mostly useful for calling configure).
+# prep-deb-files from module-assistant creates the neccessary debian/ files
+kdist_config: prep-deb-files
+
+# the kdist_clean target is called by make-kpkg modules_clean and from
+# kdist* rules. It is responsible for cleaning up any changes that have
+# been made by the other kdist_commands (except for the .deb files created)
+kdist_clean: clean
+	dh_testdir
+	dh_clean
+	# SDK=$(realpath .) LINUX_UAPI_SPLIT=1 DEBIAN_LINUX_HEADER=1 BUILD_KNET_CB=1 \
+	#     KERNDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
+	#     KERNEL_SRC=/usr/src/linux-headers-$(KERNVERSION)-amd64 \
+	#     $(MAKE) -C systems/linux/user/x86-smp_generic_64-2_6 clean
+	# SDK=$(realpath .) BUILD_KNET_CB=1 \
+	#     KDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
+	#     $(MAKE) -C sdklt/ clean
+#	rm -f driver/*.o driver/*.ko
+#
+### end  KERNEL SETUP
+
+configure: configure-stamp
+configure-stamp:
+	dh_testdir
+	# Add here commands to configure the package.
+
+	touch configure-stamp
+
+
+build-arch: configure-stamp  build-arch-stamp
+build-arch-stamp: sdk_env sdk
+	dh_testdir
+
+	# create links
 	# cd /; sudo mkdir -p /lib/modules/$(KERNVERSION)-amd64
 	# cd /; sudo rm /lib/modules/$(KERNVERSION)-amd64/build
 	# cd /; sudo rm /lib/modules/$(KERNVERSION)-amd64/source
@@ -124,34 +172,121 @@ build: prepare_sdk sdk
 	# cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/include/config/ /usr/src/linux-headers-$(KERNVERSION)-common/include/config
 	# cd /; sudo cp /usr/src/linux-headers-$(KERNVERSION)-amd64/Module.symvers /usr/src/linux-headers-$(KERNVERSION)-common/Module.symvers
 
-	# # Add here command to compile/build the package.
-	# SDK=/sonic/src/OpenBCM/sdk-6.5.21 \
-	# LINUX_UAPI_SPLIT=1 DEBIAN_LINUX_HEADER=1 BUILD_KNET_CB=1 \
-	# BUILD_SDKLT=1 BUILD_AAPL=1 LTSW_CHIPS=1 SYSOK=1 \
-	# KERNDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
-	# KERNEL_SRC=/usr/src/linux-headers-$(KERNVERSION)-amd64 \
-	# KDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
-	# $(MAKE) -C $(SDK)/systems/bde/linux/user CFLAGS="$(CFLAGS) -I$(SDK)/systems/bde/linux/include"
+	# Add here command to compile/build the package.
+	# SDK=$(realpath .) LINUX_UAPI_SPLIT=1 DEBIAN_LINUX_HEADER=1 BUILD_KNET_CB=1 \
+	#     KERNDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
+	#     KERNEL_SRC=/usr/src/linux-headers-$(KERNVERSION)-amd64 \
+	#     $(MAKE) -C systems/linux/user/x86-smp_generic_64-2_6
 
-	# $(MAKE) sdk
+	# SDK=$(realpath .) BUILD_KNET_CB=1 \
+	#     KDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
+	#     $(MAKE) -C sdklt/ kmod
 
-binary:
-
-install:
-	echo "From install ---"
-	# # create links
-	# cd /; sudo mkdir -p /lib/modules/$(KERNVERSION)-amd64
-	# cd /; sudo rm /lib/modules/$(KERNVERSION)-amd64/build
-	# cd /; sudo rm /lib/modules/$(KERNVERSION)-amd64/source
-	# cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-common/ /lib/modules/$(KERNVERSION)-amd64/source
-	# cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/ /lib/modules/$(KERNVERSION)-amd64/build
-	# cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/include/generated/ /usr/src/linux-headers-$(KERNVERSION)-common/include/generated
-	# cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/arch/x86/include/generated/ /usr/src/linux-headers-$(KERNVERSION)-common/arch/x86/include/generated
-	# cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/arch/x86/module.lds /usr/src/linux-headers-$(KERNVERSION)-common/arch/x86/module.lds
-	# cd /; sudo ln -s /usr/src/linux-headers-$(KERNVERSION)-amd64/include/config/ /usr/src/linux-headers-$(KERNVERSION)-common/include/config
-	# cd /; sudo cp /usr/src/linux-headers-$(KERNVERSION)-amd64/Module.symvers /usr/src/linux-headers-$(KERNVERSION)-common/Module.symvers
-
-	# # Add here command to compile/build the package.
-	# make -n -f Makefile.sdk V=1
+	# touch $@
 
 #k = $(shell echo $(KVERS) | grep -q ^2.6 && echo k)
+
+build-indep:  configure-stamp build-indep-stamp
+build-indep-stamp:
+	dh_testdir
+
+	# Add here command to compile/build the arch indep package.
+	# It's ok not to do anything here, if you don't need to build
+	#  anything for this package.
+	#docbook-to-man debian/openbcm.sgml > openbcm.1
+
+	touch $@
+
+build: build-arch
+
+clean:
+	dh_testdir
+	#dh_testroot
+	rm -f build-arch-stamp build-indep-stamp configure-stamp
+
+	# Add here commands to clean up after the build process.
+	# SDK=$(realpath .) LINUX_UAPI_SPLIT=1 DEBIAN_LINUX_HEADER=1 BUILD_KNET_CB=1 \
+	#     KERNDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
+	#     KERNEL_SRC=/usr/src/linux-headers-$(KERNVERSION)-amd64 \
+	#     $(MAKE) -C systems/linux/user/x86-smp_generic_64-2_6 clean
+
+	# SDK=$(realpath .) BUILD_KNET_CB=1 \
+	#     KDIR=/usr/src/linux-headers-$(KERNVERSION)-common \
+	#     $(MAKE) -C sdklt/ clean
+
+	dh_clean
+
+install: DH_OPTIONS=
+install: build
+	dh_testdir
+	dh_testroot
+	dh_prep
+	dh_installdirs
+	dh_install
+
+# Build architecture-independent files here.
+# Pass -i to all debhelper commands in this target to reduce clutter.
+binary-indep: build install
+	dh_testdir -i
+	dh_testroot -i
+	dh_installchangelogs  -i
+	dh_installdocs -i
+	dh_installexamples -i
+#	dh_install -i
+#	dh_installmenu -i
+#	dh_installdebconf -i
+#	dh_installlogrotate -i
+#	dh_installemacsen -i
+#	dh_installpam -i
+#	dh_installmime -i
+#	dh_installinit -i
+#	dh_installcron -i
+#	dh_installinfo -i
+	dh_installman -i
+	dh_link -i
+	dh_compress -i
+	dh_fixperms -i
+	dh_installdeb -i
+#	dh_perl -i
+#	dh_makeshlibs -i
+	dh_installdeb -i
+	dh_shlibdeps -i
+	dh_gencontrol -i
+	dh_md5sums -i
+	dh_builddeb -i --filename $(PKG_NAME)
+
+# Build architecture-dependent files here.
+binary-arch: build install
+	dh_testdir -s
+	dh_testroot -s
+#	dh_installdebconf -s
+
+	dh_installdocs -s
+	dh_installexamples -s
+	dh_installmenu -s
+#	dh_installlogrotate -s
+#	dh_installemacsen -s
+#	dh_installpam -s
+#	dh_installmime -s
+	dh_installmodules -s
+	dh_systemd_enable -s
+	dh_installinit -s
+	dh_systemd_start -s
+	dh_installcron -s
+#	dh_installman -s
+	dh_installinfo -s
+	dh_installchangelogs  -s
+	dh_strip -s
+	dh_link -s
+	dh_compress -s
+	dh_fixperms -s
+	dh_makeshlibs -s
+	dh_installdeb -s
+#	dh_perl -s
+	dh_shlibdeps -s
+	dh_gencontrol -s -- -n"$(PKG_NAME)"
+	dh_md5sums -s
+	dh_builddeb -s --filename $(PKG_NAME)
+
+binary: binary-indep binary-arch
+.PHONY: build clean binary-indep binary-arch binary install configure binary-modules kdist kdist_configure kdist_image kdist_clean
